# Generated by Django 4.1 on 2022-09-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('birthday', models.DateField()),
                ('color', models.CharField(max_length=150, verbose_name='color')),
                ('temperament', models.CharField(blank=True, max_length=35, null=True, verbose_name='temperament')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
            },
        ),
    ]
