# Generated by Django 4.1 on 2022-09-01 20:15

import django.core.validators
from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=src.base.services.get_path_upload_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), src.base.services.validate_size_image], verbose_name='avatar'),
        ),
    ]
